debug msgs in assemble

diff --git a/spring-boot/springboot-sti/.sti/bin/assemble b/spring-boot/springboot-sti/.sti/bin/assemble
--- a/spring-boot/springboot-sti/.sti/bin/assemble
+++ b/spring-boot/springboot-sti/.sti/bin/assemble
@@ -19,10 +19,10 @@ fi
 #   echo "---> Restoring build artifacts"
 #   mv /tmp/artifacts/. ./
 # fi
-# 
+#
 # echo "---> Installing application source"
 # cp -Rf /tmp/src/. ./
-# 
+#
 # echo "---> Building application from source"
 # # TODO: Add build steps for your application, eg npm install, bundle install
 
@@ -62,6 +62,11 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
 
   echo "Maven version:"
   mvn --version
+
+	echo "HOME: $HOME"
+	echo "HOME/.m2:"
+	ls -l $HOME/.m2
+	cat $HOME/.m2/settings.xml
 
   # Execute the actual build
   mvn -e $BUILDER_ARGS
@@ -133,7 +138,7 @@ fi
 # As SpringBoot you should only have 1 fat jar
 if [ $(ls /opt/openshift/*.jar | wc -l) -eq 1 ]; then
   mv /opt/openshift/*.jar /opt/openshift/app.jar
-  [ ! -f /opt/openshift/app.jar ] && echo "Application could not be properly built." && exit 1 
+  [ ! -f /opt/openshift/app.jar ] && echo "Application could not be properly built." && exit 1
   echo "Application jar file is located in /opt/openshift/app.jar"
 else
   echo "Whoa.  More than one jar file found!  This builder assumes you have a single (fat) jar."
